### ISSUE TITLE
Update Mockup

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2-exercise/rails-intro-exercise#10]
Currently, the README of the exercise (in the Tips Section) links to a mockup (https://gomockingbird.com/mockingbird/index.html?project=v890g6l#v890g6l/OQMURm). It's outdated, i.e., author selection uses a multiple select in the current version of the exercise. Unfortunately, we don't have the login for the gomockingbird account anymore... So the mockup would have to be recreated 😔

@LoWanda Is the mockup actually helpful in for participants? Should it be updated? Or maybe placed more prominently?

**Comment by LoWanda** [comment]
I don't think the mockup is needed to successfully complete the exercise (I can actually not remember looking at it at all last year). It may be a nice reference if you are stuck, but in the end the Management System you are supposed to build is simple enough to imagine the different links, text fields, etc. by yourself. And the Rails Tutorial also has some pictures that show how it is supposed to look like. 
I think we can leave it in the Tips section for those who need the visual guidance, but I don't think it needs to be updated to be a good reference.

**Comment by chrisma** [comment]
Alright. Thanks for your input!
